import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between items-center px-4 py-2">
          <Link href="/">Logo</Link>
          <div className="flex justify-between px-4 gap-6 colors-blue">
            <Link href="/">Home</Link>
            <Link href="/blog">blog</Link>

          </div>

        </nav>
        {children}
      </body>
    </html>
  );
}
